### ISSUE TITLE
Improve the full font report.

### ISSUE THREAD

**Issue by typesupply** [typesupply/glyph-nanny#12]
The dumped output is fine, but it would be much nicer in a new window with an HTML view. It would also be nice to add an option for marking any glyphs with problems with a single color. I'd only do that if @luke-snider is okay with it, though.

**Comment by typesupply** [comment]
Idea: in the HTML output, include a visualization of the marked up glyph with the notes. It should be possible to lock focus on NSImage, go through the drawing sequence manually, unlock focus, get the image data as a PNG (or whatever) and embed it in the HTML.

**Comment by luke-snider** [comment]
sounds great!

**Comment by typesupply** [comment]
Done in 2982c296494a2aa4b7bf7584d4d57554ad6d514c and 65aba008878852505a5290c226c564a175716439.
