### ISSUE TITLE
Make Glyph Nanny work with the new master of defcon.

### ISSUE THREAD

**Issue by typesupply** [typesupply/glyph-nanny#38]
- Representation factories moved.
- Most objects can have their own representations now.

**Comment by typemytype** [comment]
I would propose to move registration of representations to a startUp script. You don't have to test it anymore and you are sure it will be executed only once, during startup

https://github.com/typesupply/glyph-nanny/blob/89b0f6fd47e9f11595413e2a15efcbd82baf4817/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py#L683

**Comment by typemytype** [comment]
you could use `version` to test  

```
from mojo.roboFont import version
print version
```

**Comment by typesupply** [comment]
Done in the Merz rebuild.
