### ISSUE TITLE
Running live report makes system run out of memory

### ISSUE THREAD

**Issue by rsms** [typesupply/glyph-nanny#39]
What I did:
- Opened [Interface-Regular (specific version linked)](https://github.com/rsms/interface/tree/31ae014e0c827d/src/Interface-Regular.ufo)
- Ran full report on that font
- After a minute, macOS suspended RoboFont as it had used up all of the available memory and had to be force-quit. My machine has 16 GB of memory plus another 100 GB of SSD for virtual memory.

Environment:
- macOS 10.12.6 (16G29)
- MacBookPro11,5 with 16 GB memory
- RoboFont 1.8.4 (built 1706131209)
- Glyph Nanny 84ae8931849288d1ddcc3c97ccf6803207427ce6

<img width="376" alt="screen shot 2017-09-04 at 12 00 41" src="https://user-images.githubusercontent.com/47046/30033423-338bd1c2-9169-11e7-9aab-1045d94236ae.png">

<img width="413" alt="screen shot 2017-09-04 at 11 59 02" src="https://user-images.githubusercontent.com/47046/30033427-363b5d34-9169-11e7-98d9-4a7ae3516910.png">

**Comment by rsms** [comment]
You might want to consider processing information in a streaming manner (not buffering everything in memory), or only keeping relevant data in memory if buffering is neccessary.

**Comment by typesupply** [comment]
I downloaded the font you referenced and I get the same error message. My hunch is that it is the [function](https://github.com/typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py#L484) that generates a PNG for each glyph. That's making a pretty big image for each glyph and holding the data as base64 for embedding in HTML. The NSImage object and friends used during that process could also be causing some leaks or generating objects that aren't freed when no longer used.

I don't have time to test this right now, but the way to confirm this would be to:

1. Remove the PNG reference [here](https://github.com/typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py#L480).
2. Eliminate the PNG generation [here](https://github.com/typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py#L414).
3. Eliminate the PNG insertion [here](https://github.com/typesupply/glyph-nanny/blob/master/Glyph%20Nanny.roboFontExt/lib/glyphNanny.py#L418).

If someone out there could try this, I'd really appreciate it. If it does fix the issue, I'll make the PNG generation optional and raise a warning before generating a report containing PNGs for a font with > 250 glyphs. If this doesn't fix the issue, I'll dig deeper.

**Comment by typesupply** [comment]
This should be fixed.
