### ISSUE TITLE
Duplicate component with same position and scale

### ISSUE THREAD

**Issue by typoman** [typesupply/glyph-nanny#40]
The extension recognizes a duplicated contour in same glyph but I thought duplicated component could also be added since it's not recognized yet by the extension?

**Comment by typemytype** [comment]
added here https://github.com/typesupply/glyph-nanny/commit/cafd1a8c9ec0f2ca6763fe4828aad6d06ef6bed4

could you test by [manually download this extension](https://github.com/typesupply/glyph-nanny/archive/master.zip), before I touch the version number and set a notification on Mechanic

thanks!

**Comment by typoman** [comment]
Works in all versions. Thanks :)
