### ISSUE TITLE
White spots visible on dark background

### ISSUE THREAD

**Issue by nicksherman** [typesupply/glyph-nanny#60]
Changing the background color of RoboFont’s glyph view to a dark color (e.g. for a dark mode theme) reveals 2 white spots that Glyph Nanny seems to be adding near the origin point, even when the live reporting is disabled. At least I think it's from Glyph Nanny(?) … When I uninstall the extension and restart RoboFont the spots are no longer visible.

![Screenshot 2023-02-22 at 05 13 28](https://user-images.githubusercontent.com/1265313/220592730-4eac026d-e3c2-4a5d-aa30-eef88d434584.png)

**Comment by typemytype** [comment]
these two are floating around when no text is displayed https://github.com/typesupply/glyph-nanny/blob/d629ef3b88afd89a60faaaa2f9a9808a69e13dbe/build/Glyph%20Nanny.roboFontExt/lib/glyphNanny/editorLayers.py#L162-L172

**Comment by typemytype** [comment]
could you test that branch version before merging the PR?
direct download link -> https://github.com/typesupply/glyph-nanny/archive/refs/heads/whiteBackground.zip

**Comment by nicksherman** [comment]
That fixes it, thanks!
